# Generated by Django 2.2 on 2021-09-26 23:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letters', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=[], size=None, verbose_name='Letters')),
                ('letters_hash', models.CharField(max_length=255, verbose_name='Letters Hash')),
                ('is_valid', models.BooleanField(default=False, verbose_name='Is Valid')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
            ],
            options={
                'verbose_name': 'Sequence',
                'verbose_name_plural': 'Sequences',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='sequence',
            index=models.Index(fields=['letters_hash'], name='sequence_ba_letters_92242d_idx'),
        ),
    ]
